### ISSUE TITLE
Generated CRD schemas have issues for IntOrString fields

### ISSUE THREAD

**Issue by yuqi-zhang** [openshift/build-machinery-go#11]
Not entirely sure if this is the right place to report this. When I tried using this to generate schemas for the machine-config-operator, and it generated a snippet as follows:
```
           maxUnavailable:
              description: maxUnavailable specifies the percentage or constant number
                of machines that can be updating at any given time. default is 1.
              anyOf:
              - type: string
              - type: integer
```
Which resulted in an error when attempting to apply:
```
* spec.validation.openAPIV3Schema.properties[spec].properties[maxUnavailable].anyOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[maxUnavailable].anyOf[1].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[maxUnavailable].type: Required value: must not be empty for specified object fields
```

From https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#intorstring it should be 
```
           maxUnavailable:
              description: maxUnavailable specifies the percentage or constant number
                of machines that can be updating at any given time. default is 1.
              anyOf:
              - type: integer
              - type: string
              x-kubernetes-int-or-string: true
```
instead.

Looking upstream this seems to have been fixed in https://github.com/kubernetes-sigs/controller-tools/pull/360 ?
